version: '3'

networks:
  adonis5:
    external: true

volumes:
  postgres_data:

services:
  api:
    build: .
    image: tgl
    ports:
      - '3333:3333'
    volumes:
      - ./:/home/node/app/
    networks:
      - adonis5
    depends_on:
      - redis
      - migration

  migration:
    build: .
    # restart: always
    image: tgl
    networks:
      - adonis5
    command: node ace migration:run
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tgl
    ports:
      - '5433:5432'
    networks:
      - adonis5

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - adonis5
